### ISSUE TITLE
Update Apache Incubator logo

### ISSUE THREAD

**Issue by krook** [apache/openwhisk-website#212]
Here's the latest guidance: http://incubator.apache.org/guides/press-kit.html

**Comment by mrutkows** [comment]
Apache just release a new logo for Apache Incubator projects, along with guidance on how to incorporate project logos. Find this all described here: http://incubator.apache.org/guides/press-kit.html

At min. we should add the Apache Incubator logo (perhaps on our footer of all pages) and also seek to create approved logos/graphics that incorporate the OpenWhisk logo for project use. 

Closing duplicate issue https://github.com/openwhisk/openwhisk.github.io/issues/214 since it  appears we were thinking the same thing at the same time (upon receiving the email from Apache).

**Comment by krook** [comment]
Still need to create the high res ones as mentioned on the dev list: https://lists.apache.org/thread.html/78dc0fa95fb0a16bf7202a6cca0c5b731633359fe67420bbfcd83694@%3Cdev.openwhisk.apache.org%3E

**Comment by mrutkows** [comment]
With the website redesign, I would recommend placing the "incubator" logo in the Footer (alongside the disclaimer). See http://incubator.apache.org/guides/press-kit.html

**Comment by dgrove-oss** [comment]
Closing as done?  Incubator logo no longer relevant and I believe we have appropriate OpenWhisk logos in all the right places.
